create table
  public.tokens (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    uid uuid not null,
    token jsonb not null,
    account_service text not null,
    account_name text not null,
    digits numeric not null,
    constraint tokens_pkey primary key (id)
  ) tablespace pg_default;