create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    email text not null,
    password text not null,
    salt text not null,
    uid uuid not null default gen_random_uuid (),
    created_ip text not null,
    lastsignin_ip text null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_uid_key unique (uid)
  ) tablespace pg_default;