export const selectValues = {
    1: "Amazon Web Services",
    2: "Amazon",
    3: "DigitalOcean",
    4: "Discord",
    5: "Dropbox",
    6: "Evernote",
    7: "Facebook",
    8: "GitHub",
    9: "Google",
    10: "Heroku",
    11: "IFTTT",
    12: "Linode",
    13: "Microsoft",
    14: "Slack",
    15: "Snapchat",
    16: "Stripe",
    17: "TeamViewer",
    18: "Twitter (X)",
    19: "WordPress",
    20: "Zoom",
    21: "Other"
};